/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TricksforBoosterNFT } from "./TricksforBoosterNFT";
export type { TricksforBoosterStaking } from "./TricksforBoosterStaking";
