/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TricksforBoosterNFT__factory } from "./TricksforBoosterNFT__factory";
export { TricksforBoosterStaking__factory } from "./TricksforBoosterStaking__factory";
